-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 00:11:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema azil
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `azil` ;

-- -----------------------------------------------------
-- Schema azil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `azil` DEFAULT CHARACTER SET utf8 ;
USE `azil` ;

-- -----------------------------------------------------
-- Table `azil`.`Zaposleni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Zaposleni` ;

CREATE TABLE IF NOT EXISTS `azil`.`Zaposleni` (
  `JMBG` CHAR(13) NOT NULL,
  `Ime` VARCHAR(255) NOT NULL,
  `Prezime` VARCHAR(255) NOT NULL,
  `Username` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `StrucnaSprema` VARCHAR(255) NULL,
  `MjestoPrebivalista` VARCHAR(255) NULL,
  `BrojTelefona` VARCHAR(255) NULL,
  PRIMARY KEY (`JMBG`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`UgovorORadu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`UgovorORadu` ;

CREATE TABLE IF NOT EXISTS `azil`.`UgovorORadu` (
  `IdUgovora` INT NOT NULL AUTO_INCREMENT,
  `Pozicija` VARCHAR(255) NOT NULL,
  `Aktivan` TINYINT(1) NOT NULL,
  `Plata` DECIMAL NOT NULL,
  PRIMARY KEY (`IdUgovora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Zaposleni_Ugovor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Zaposleni_Ugovor` ;

CREATE TABLE IF NOT EXISTS `azil`.`Zaposleni_Ugovor` (
  `Od` DATE NOT NULL,
  `ZaposlenikJMBG` CHAR(13) NOT NULL,
  `IdUgovora` INT NOT NULL,
  `Do` DATE NULL,
  PRIMARY KEY (`Od`, `ZaposlenikJMBG`, `IdUgovora`),
  INDEX `fk_Zaposlenik_Ugovor_Zaposlenik_idx` (`ZaposlenikJMBG` ASC),
  INDEX `fk_Zaposlenik_Ugovor_UgovorORadu1_idx` (`IdUgovora` ASC),
  CONSTRAINT `fk_Zaposlenik_Ugovor_Zaposlenik`
    FOREIGN KEY (`ZaposlenikJMBG`)
    REFERENCES `azil`.`Zaposleni` (`JMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zaposlenik_Ugovor_UgovorORadu1`
    FOREIGN KEY (`IdUgovora`)
    REFERENCES `azil`.`UgovorORadu` (`IdUgovora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Sluzbenik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Sluzbenik` ;

CREATE TABLE IF NOT EXISTS `azil`.`Sluzbenik` (
  `SluzbenikJMBG` CHAR(13) NOT NULL,
  PRIMARY KEY (`SluzbenikJMBG`),
  CONSTRAINT `fk_Sluzbenik_Zaposlenik1`
    FOREIGN KEY (`SluzbenikJMBG`)
    REFERENCES `azil`.`Zaposleni` (`JMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Veterinar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Veterinar` ;

CREATE TABLE IF NOT EXISTS `azil`.`Veterinar` (
  `VeterinarJMBG` CHAR(13) NOT NULL,
  PRIMARY KEY (`VeterinarJMBG`),
  CONSTRAINT `fk_Veterinar_Zaposlenik1`
    FOREIGN KEY (`VeterinarJMBG`)
    REFERENCES `azil`.`Zaposleni` (`JMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `azil`.`Administrator` (
  `AdministratorJMBG` CHAR(13) NOT NULL,
  PRIMARY KEY (`AdministratorJMBG`),
  CONSTRAINT `fk_Administrator_Zaposlenik1`
    FOREIGN KEY (`AdministratorJMBG`)
    REFERENCES `azil`.`Zaposleni` (`JMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Pas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Pas` ;

CREATE TABLE IF NOT EXISTS `azil`.`Pas` (
  `IdPsa` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(255) NOT NULL,
  `Pol` CHAR(1) NOT NULL,
  `Rasa` VARCHAR(255) NOT NULL,
  `DatumRodjenja` DATE NULL,
  `Visina` INT NULL,
  `Tezina` DOUBLE NULL,
  `Fotografija` VARCHAR(255) NULL,
  `Udomljen` TINYINT NULL,
  `Obrisan` TINYINT NULL,
  PRIMARY KEY (`IdPsa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Nalaz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Nalaz` ;

CREATE TABLE IF NOT EXISTS `azil`.`Nalaz` (
  `IdNalaza` INT NOT NULL AUTO_INCREMENT,
  `DatumPregleda` DATE NULL,
  `Dijagnoza` LONGTEXT NULL,
  `VeterinarJMBG` CHAR(13) NOT NULL,
  `IdPsa` INT NOT NULL,
  PRIMARY KEY (`IdNalaza`),
  INDEX `fk_Nalaz_Veterinar1_idx` (`VeterinarJMBG` ASC),
  INDEX `fk_Nalaz_Pas1_idx` (`IdPsa` ASC),
  CONSTRAINT `fk_Nalaz_Veterinar1`
    FOREIGN KEY (`VeterinarJMBG`)
    REFERENCES `azil`.`Veterinar` (`VeterinarJMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nalaz_Pas1`
    FOREIGN KEY (`IdPsa`)
    REFERENCES `azil`.`Pas` (`IdPsa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Lijek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Lijek` ;

CREATE TABLE IF NOT EXISTS `azil`.`Lijek` (
  `IdLijeka` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(255) NOT NULL,
  `Opis` TEXT NULL,
  `Kolicina` INT NOT NULL,
  PRIMARY KEY (`IdLijeka`),
  UNIQUE INDEX `NazivLijeka_UNIQUE` (`Naziv` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`DodavanjeLijeka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`DodavanjeLijeka` ;

CREATE TABLE IF NOT EXISTS `azil`.`DodavanjeLijeka` (
  `VrijemeDodavanja` DATETIME NOT NULL,
  `SluzbenikJMBG` CHAR(13) NOT NULL,
  `IdLijeka` INT NOT NULL,
  `Kolicina` INT NULL,
  PRIMARY KEY (`VrijemeDodavanja`, `SluzbenikJMBG`, `IdLijeka`),
  INDEX `fk_DodavanjeLijeka_Sluzbenik1_idx` (`SluzbenikJMBG` ASC),
  INDEX `fk_DodavanjeLijeka_Lijek1_idx` (`IdLijeka` ASC),
  CONSTRAINT `fk_DodavanjeLijeka_Sluzbenik1`
    FOREIGN KEY (`SluzbenikJMBG`)
    REFERENCES `azil`.`Sluzbenik` (`SluzbenikJMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DodavanjeLijeka_Lijek1`
    FOREIGN KEY (`IdLijeka`)
    REFERENCES `azil`.`Lijek` (`IdLijeka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`UzimanjeLijeka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`UzimanjeLijeka` ;

CREATE TABLE IF NOT EXISTS `azil`.`UzimanjeLijeka` (
  `DatumUzimanja` DATETIME NOT NULL,
  `VeterinarJMBG` CHAR(13) NOT NULL,
  `IdLijeka` INT NOT NULL,
  `IdNalaza` INT NOT NULL,
  `Kolicina` INT NOT NULL,
  PRIMARY KEY (`DatumUzimanja`, `VeterinarJMBG`, `IdLijeka`, `IdNalaza`),
  INDEX `fk_UzimanjeLijeka_Lijek1_idx` (`IdLijeka` ASC),
  INDEX `fk_UzimanjeLijeka_Nalaz1_idx` (`IdNalaza` ASC),
  INDEX `fk_UzimanjeLijeka_Veterinar1_idx` (`VeterinarJMBG` ASC),
  CONSTRAINT `fk_UzimanjeLijeka_Lijek1`
    FOREIGN KEY (`IdLijeka`)
    REFERENCES `azil`.`Lijek` (`IdLijeka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UzimanjeLijeka_Nalaz1`
    FOREIGN KEY (`IdNalaza`)
    REFERENCES `azil`.`Nalaz` (`IdNalaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UzimanjeLijeka_Veterinar1`
    FOREIGN KEY (`VeterinarJMBG`)
    REFERENCES `azil`.`Veterinar` (`VeterinarJMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Kavez`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Kavez` ;

CREATE TABLE IF NOT EXISTS `azil`.`Kavez` (
  `IdKaveza` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(255) NOT NULL,
  `Kapacitet` INT NOT NULL,
  `Ukupno` INT NOT NULL,
  PRIMARY KEY (`IdKaveza`),
  UNIQUE INDEX `NazivKaveza_UNIQUE` (`Naziv` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Kavez_Pas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Kavez_Pas` ;

CREATE TABLE IF NOT EXISTS `azil`.`Kavez_Pas` (
  `Od` DATETIME NOT NULL,
  `IdKaveza` INT NOT NULL,
  `IdPsa` INT NOT NULL,
  `Do` DATETIME NULL,
  PRIMARY KEY (`IdKaveza`, `IdPsa`, `Od`),
  INDEX `fk_Kavez_Pas_Kavez1_idx` (`IdKaveza` ASC),
  INDEX `fk_Kavez_Pas_Pas1_idx` (`IdPsa` ASC),
  CONSTRAINT `fk_Kavez_Pas_Kavez1`
    FOREIGN KEY (`IdKaveza`)
    REFERENCES `azil`.`Kavez` (`IdKaveza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kavez_Pas_Pas1`
    FOREIGN KEY (`IdPsa`)
    REFERENCES `azil`.`Pas` (`IdPsa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Udomitelj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Udomitelj` ;

CREATE TABLE IF NOT EXISTS `azil`.`Udomitelj` (
  `JMBG` CHAR(13) NOT NULL,
  `Ime` VARCHAR(255) NOT NULL,
  `Prezime` VARCHAR(255) NOT NULL,
  `Adresa` VARCHAR(255) NULL,
  `BrojTelefona` VARCHAR(255) NULL,
  PRIMARY KEY (`JMBG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`UdomljavanjePsa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`UdomljavanjePsa` ;

CREATE TABLE IF NOT EXISTS `azil`.`UdomljavanjePsa` (
  `DatumOd` DATE NOT NULL,
  `IdPsa` INT NOT NULL,
  `UdomiteljJMBG` CHAR(13) NOT NULL,
  `DatumDo` DATE NULL,
  PRIMARY KEY (`DatumOd`, `IdPsa`, `UdomiteljJMBG`),
  INDEX `fk_UdomljavanjePsa_Pas1_idx` (`IdPsa` ASC),
  INDEX `fk_UdomljavanjePsa_Udomitelj1_idx` (`UdomiteljJMBG` ASC),
  CONSTRAINT `fk_UdomljavanjePsa_Pas1`
    FOREIGN KEY (`IdPsa`)
    REFERENCES `azil`.`Pas` (`IdPsa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UdomljavanjePsa_Udomitelj1`
    FOREIGN KEY (`UdomiteljJMBG`)
    REFERENCES `azil`.`Udomitelj` (`JMBG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azil`.`Logger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azil`.`Logger` ;

CREATE TABLE IF NOT EXISTS `azil`.`Logger` (
  `LoggerID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NOT NULL,
  `Datum` DATETIME NOT NULL,
  `Opis` TEXT NOT NULL,
  PRIMARY KEY (`LoggerID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
